# Generated by Django 2.0.7 on 2018-07-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0004_post_created_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
    ]
