# Generated by Django 2.0.7 on 2018-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_auto_20180720_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='final_score',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
