# Generated by Django 2.0.7 on 2018-07-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0009_auto_20180725_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
