# Generated by Django 2.0.7 on 2018-10-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0014_auto_20180818_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
